### ISSUE TITLE
Build fails with perl 5.26.0 on High Sierra

### ISSUE THREAD

**Issue by burak** [mbarbon/google-protobuf-dynamic#19]
Logs attached.

[cpan-build.txt](https://github.com/mbarbon/google-protobuf-dynamic/files/2053867/cpan-build.txt)
[perl-version.txt](https://github.com/mbarbon/google-protobuf-dynamic/files/2053868/perl-version.txt)

**Comment by mbarbon** [comment]
Hi Burak,

I do not have a Perl/Mac build environment, but I pushed a blind fix.

Could you try building master and see if it works now?

Thanks!
Mattia

**Comment by burak** [comment]
Hi Mattia,

That's sub-optimal for testing :) Thanks for the patch but it still fails. but with new errors
[new-log.txt](https://github.com/mbarbon/google-protobuf-dynamic/files/2062609/new-log.txt)


```
:google-protobuf-dynamic bgursoy$ git log | head -4
commit a75e137b53cd2ba0fb5c352279131267d26052b9
Author: Mattia Barbon <mattia@barbon.org>
Date:   Thu May 31 20:32:53 2018 +0200

:google-protobuf-dynamic bgursoy$ dzil test > /tmp/new-log.txt 2>&1
```

**Comment by mbarbon** [comment]
After testing on a Mac, it works for me.

Looking at the linking error, one possible cause is that, at some point you upgraded the `protobuf` C++ library, but The uPB build installed by `Alien::uPB` was compiled against the old version and is thus missing some symbols.

If this is the case, forcing an Alien::uPB reinstall, and then cleaning and rebuilding `Google::ProtocolBuffers::Dynamic` should fix the issue.

**Comment by burak** [comment]
Hi Mattia,

Sorry I couldn't take a llok at this but you are right my system went through various macos upgrades + macports updates as well so possibly something b0rked in between. Thanks for checking. I guss it's better to close this one.
